### PR TITLE
Use special color for underline

### PR DESCRIPTION
**Pull request by jacobmischka**
Fixes #262

### CODE REVIEW

**Comment by Lyude** [comment]
Hm, seems I forget to actually test this when I reviewed this as I just noticed today that this actually just seems to have regressed underline highlighting:

Before:
image

After:
image

Not sure what changed since you made this PR, but I'm going to revert it for the time being

**Comment by jacobmischka** [comment]
That is correct behavior I believe, underline is supposed to use special color according to :help.

**Comment by jacobmischka** [comment]
I suppose maybe the issue is that `HighlightMap.sp_color` defaults to red: https://github.com/Lyude/neovim-gtk/blob/main/src/highlight.rs#L33

Maybe instead it should be an Option, and if None it would fallback to the `fg_color`.

In any event, I'm confident that this PR is the correct behavior, and should be un-reverted.

**Comment by theHamsta** [comment]
The PR @jacobmischka made it possible for the first time to see LSP warning/error underlining in the correct color. +1 for un-reverting it.

**Comment by Lyude** [comment]
Gotcha, looks like I jumped the gun with reverting this!

**Pull request merged**
