### PR TITLE
Update to try-cmd 0.15

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Review by baco — APPROVED** [review]

**Review by baco — CHANGES_REQUESTED** [review]
The build is failing

**Comment by sdroege** [comment]
Not because of my changes though. I don't know if @Lyude wants to have an unrelated commit to fix the clippy warnings here or separately. Just let me know and I'll either add them here or create a separate PR for that.

**Comment by Lyude** [comment]
> Not because of my changes though. I don't know if @Lyude wants to have an unrelated commit to fix the clippy warnings here or separately. Just let me know and I'll either add them here or create a separate PR for that.

Feel free just to add them here!

**Comment by sdroege** [comment]
Done!

**Review by baco — APPROVED** [review]

**Pull request merged**
